[server]
host = "127.0.0.1"
port = 8082


[mysql]
host = "localhost"  # 数据库 ip
port = 3306         # 数据库端口
username = "zyl"    # 用户
password = "password"   # 
db_name = "program_station"  # 数据库名称
pool_numbers = 15


[email]
username = "2812470857@qq.com"
password = "kpstnlhegwzhdhdh"   
gmail = "smtp.qq.com"



[redis]
protocol = "redis"
host = "localhost"
port = 6379
username = ""
password = ""
session_key = "runner"
max_age = 2592000  # 单位s，session过期时间，默认30天